name: Deploy Vite App to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write   # 👈 required for gh-pages push
  pages: write      # 👈 required to update Pages settings
  id-token: write   # 👈 required for deployments

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

  pages-deploy:
    needs: build-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./dist
      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
